package day01;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class ElfCode implements Runnable {
    String scrambledCode;
    @Override
    public void run() {
        List<Integer> codes = unscramble(scrambledCode);
        System.out.println(codes.stream().reduce((a, b) -> a+b));
    }

    private List<Integer> unscramble(String scrambledCode) {
        return Arrays.stream(scrambledCode.split("\n"))
                .map(this::getNumbers)
                .collect(Collectors.toList());
    }

    private int getNumbers(String code) {
        List<Integer> nums = new ArrayList<>();
        int returnVal = 0;
        char c;
        for (int i = 0; i < code.length(); i++) {
            c = code.charAt(i);
            if (Character.isDigit(c)) {
               nums.add(Integer.parseInt("" + c));
            }
        }
        System.out.println("num array is '" + nums + "'");
        if (!nums.isEmpty()){
            returnVal = 10 * nums.get(0);
            returnVal += nums.get(nums.size()-1);

        }

        System.out.println("Calibration code for '" + code + "' is '" + returnVal + "'");
        return returnVal;
    }

    public ElfCode(){
        this.scrambledCode = "threehqv2\n" +
                "sxoneightoneckk9ldctxxnffqnzmjqvj\n" +
                "1hggcqcstgpmg26lzxtltcgg\n" +
                "nrhoneightkmrjkd7fivesixklvvfnmhsldrc\n" +
                "zhlzhrkljonephkgdzsnlglmxvprlh6n\n" +
                "594chhplnzsxktjmkfpninefiveczfnvsctbxcfzfzjh\n" +
                "seven2tjf\n" +
                "five712\n" +
                "tzheightzlzmsqlnxfqzrlbhbdpbnbdjns6\n" +
                "ztwo1eight95\n" +
                "one25eightzptqnvvlnf\n" +
                "46brthree51bhvhtcnpcffoursix\n" +
                "five7bhsfdktxq33qtrmvqxfgone3\n" +
                "4f6six1skrmltxeight\n" +
                "onemhfbhrx99\n" +
                "five3eightjkdpxqtmbtwo\n" +
                "onebzp4seven4ft\n" +
                "5sxgjszzninembrtjptlfn24llbxrnm\n" +
                "sixninefivejpqgkcx3sixnine15\n" +
                "fourcmsndtdkrone75\n" +
                "68hnrkxbmvjzjzfk\n" +
                "2oneseventhreesixrbkkbhlx\n" +
                "five6npfmggbdkljqsixjnxgk1cqdmcneight\n" +
                "6eightfiveksmrbjgc\n" +
                "eight8zqjsixfivefrrbg4\n" +
                "2sixfhbnqbjv3krgqgfj\n" +
                "one56vhgnlxfjhrc6\n" +
                "8twothreelgbmx31\n" +
                "kfkjfckbhnv8threedpxhhfivepkcnfjmcpt\n" +
                "onenxqtvzvzph8nmtjgsjkone4btzxpkjfbthhsmqcqz\n" +
                "mdbsvbf8zbllzcsixclrjnfzf\n" +
                "knptlbzlffourfivetjzjpleightsix31\n" +
                "one6pbdfdtsqhjhqfourqqvkvksm\n" +
                "nxd3dkj1threeeightqxlfndjtglnxlqmb9\n" +
                "5three37tfnkz\n" +
                "57eight9fivefiveeight\n" +
                "2zd155\n" +
                "3lljdglhbfiveeight92\n" +
                "44lseven6\n" +
                "9xlv5gqgvpjvrhbbcrnmq2pt5\n" +
                "fiveeightslvzrvvgfsrvnsnhk1\n" +
                "twotsffgflt1two9four24three\n" +
                "2fourstszszgmxfive6fourzx\n" +
                "nine8bgh921seven\n" +
                "threevbvcrmqfivesix6fivenrxd22\n" +
                "zmdhdgfrr4przvs1\n" +
                "jpxt9\n" +
                "five6fivethree2three\n" +
                "qmz45cbtvx535\n" +
                "7eighttfbrsmvtpnsjcjpsjxcnine67two\n" +
                "nllgnjsdlkkng6ninesixjpjlmjg\n" +
                "two6615sixg2\n" +
                "7onetwoninemhjlqmlkkt\n" +
                "fourfffqcsmxc5nsixpncjnvpm5\n" +
                "rbbmltgpsixfive8nine4sevenfour\n" +
                "vfzmncfonexxkzlcstqhxvtwoplsglsix1kpkssfz\n" +
                "twojsrsixone39eight\n" +
                "three5nine\n" +
                "fcgx5pvnsxnhfd\n" +
                "9krnchzvnv8one\n" +
                "ninetwo1\n" +
                "eightrtvgkfjn1tfgxqeightseventwo\n" +
                "255five9\n" +
                "bxkg53\n" +
                "5vdr8\n" +
                "threetwomxbgqhzdq3\n" +
                "6dlg51p3\n" +
                "q53\n" +
                "8seven6594five\n" +
                "sixeightnpdsfdjljtwofiveqm7two2\n" +
                "qxsrbthree24four2\n" +
                "jbzeighteightpksq1twokcsvsr8\n" +
                "7kmmkdcmbl\n" +
                "twonvfhlseven7qksvksixqfz\n" +
                "8hbffjsbckqcscsevenbztnmvvg\n" +
                "one5kntjln21\n" +
                "2sevenlt7threesix49jkdtqqr\n" +
                "6drqlvfour1nine\n" +
                "6zmk8n\n" +
                "one279seven\n" +
                "65eightssvjkchfhrpdhlmrbrsevenkrpt7\n" +
                "dj87\n" +
                "sixsevendxvjjseight4two3tpvbcbf\n" +
                "4eightzz8three5\n" +
                "95gsfb5sevennhgmdc\n" +
                "plpn2threesix\n" +
                "seven22\n" +
                "8eightqqcgzd6ldh\n" +
                "4sixvsmhtlfcmbnmzgnsixfour\n" +
                "kmncbxcgmxmt1nine\n" +
                "4kb6one\n" +
                "threefivefivefourfive9npqtvvr3\n" +
                "cjkpsc5ninepkcqpvnkzcr\n" +
                "glzvgvpjvhsixbgdvzfive97mdbxtlvz7srhtpsfk\n" +
                "8three9dnzfgjzmzhh5seven\n" +
                "sevenfkqpshm6mx\n" +
                "9onedbvnnmfl15\n" +
                "sstcrnkkbzfsfcnkone8\n" +
                "xtqzchjspfdtsoneninethree4sixffsix\n" +
                "584ptgjtlqktk\n" +
                "kknpxzc26\n" +
                "pghjgrxh4135ttxr\n" +
                "2pjgp8one49\n" +
                "five3qjqsdstkq5ninevfzjgkpxphone82\n" +
                "fllgbdnbsztbfnjmhone7five\n" +
                "cgpqqcbfksnvppdqqsgh7twotzqglbvptmfive\n" +
                "2three6twozchrbnjsxdqtmfppzmr34\n" +
                "89kfjsix\n" +
                "3mpk7\n" +
                "3threekcgjfkk425\n" +
                "39zxtkntmxt\n" +
                "13ninevvrsxn436fivethree\n" +
                "nine5dphhllslr8nktvcd\n" +
                "7fourfourfivevbnlgzgxnpt\n" +
                "2hjvmsxfmfxtlljnqzr\n" +
                "6onepjqmjlsvfourfour2three\n" +
                "5kzsfrfmflp7twoqb4two3\n" +
                "three186threeone2\n" +
                "8four5hnineppprpkjhf\n" +
                "1qvtx1843\n" +
                "qblf36xsrdsvqhrmlrbthree\n" +
                "326sevenfivenseven1kctgmnqtwonefq\n" +
                "41sixfour\n" +
                "three4sevenone\n" +
                "4sevenptjmqgffivesix71pgpfcmc\n" +
                "14mndmdlsjhtprtxtskmdfive\n" +
                "6lrjglxqksevenkvsp5six37three\n" +
                "ljzfourjcclgcdgqcdnbhk9mrtnfrtwo\n" +
                "389six37threervldzxvlgr\n" +
                "2rtjhvsvrmtwo1hgzpeightdjkhxhmseven7\n" +
                "seven38fivepknvlmrjgbms7\n" +
                "27eightlccjptfm5rdthree4\n" +
                "cqpnjv58\n" +
                "2mbvkpzvfccrns8one52\n" +
                "three4seven7two\n" +
                "dfptdxdj8flxhqvfg8zljld\n" +
                "dm71two1hnggncbqkxsfkmq7\n" +
                "8blsrrqrjlckv7xszllqddzn5oneightfg\n" +
                "5fivej\n" +
                "fvx97jjfc63qbkpnqqqzbfmj\n" +
                "tgnzdkgfoureight9\n" +
                "37kc\n" +
                "1shthsfsdfmkmgxh2\n" +
                "6fdldj\n" +
                "sevenv79spttnzrrbvpmcf\n" +
                "ghpxgf3xk1zddlhfdnzthxmqqmzdpf\n" +
                "9f7ninethreeone\n" +
                "288vxrjxkjr78lsgbcssfdtsix\n" +
                "6vkckltsqvhsgvhtonezmrdfvn4\n" +
                "12bhseven6\n" +
                "three8bxfndbnine\n" +
                "4three14one\n" +
                "qs9twotkqgxthree\n" +
                "kbtwonesix2eight194four\n" +
                "nxjseven7\n" +
                "threejpzxfiveninet9fivetkxgzxd3\n" +
                "8fjjbghh9\n" +
                "nine8fourfourthreempcldmm\n" +
                "six24qkjpkqlrrqfiveninejnjbdld\n" +
                "zhsztjsgthreeeightone831\n" +
                "9threegpgtdm\n" +
                "8mnl31two7oneseven\n" +
                "gxdltwoonelzvbctwo91fourthree\n" +
                "lmgfive8\n" +
                "41six13kcvdsix\n" +
                "qsix9qlzjxfive8ninengxncsdpck\n" +
                "twoqmzfsrdq7\n" +
                "vqsgtzqmvslp1vnnjzvkjggn9fiveninesix\n" +
                "blrrckhs7tfpnssnpk76vkdsthree\n" +
                "znoneight925cnqsm79lplfpmzzh\n" +
                "twozqv3fourtwo\n" +
                "mscksglc3ql\n" +
                "fxf3four8dfmncxqseven\n" +
                "pdrfptqj3ndpmfiveonecz436\n" +
                "mtzzzjz23zhcbg1\n" +
                "74tflvhzjhvfivefour5bjhhkfvrfm7three\n" +
                "3246three\n" +
                "zzzzxptgsevenfoureight3sevenpq89\n" +
                "35sevenzgpptx8trrhb7seven8\n" +
                "onegfshppnb3vpvsbcvsg2qndxmpm\n" +
                "6ntfjnvdrmrzhdhgljq\n" +
                "eightlnmdkqb1\n" +
                "sevenseven2three\n" +
                "pjxvzpdtfcnine9five\n" +
                "sevenseven7\n" +
                "9rhdtwoninemclzzqhztxhljmjssevenfive3\n" +
                "6eightsthxqvfzgrlffsix7qxxdktsbseven\n" +
                "nine938zrsrhn3\n" +
                "two1fourthreetwotkvktvsspzfbfhrch27\n" +
                "29one7672\n" +
                "8zcdxmbfrhj3bqncflspd\n" +
                "bnplfntoneninesix6one\n" +
                "8one2six3one3nseven\n" +
                "seven31\n" +
                "kcfsnqz52nnkxrblnsndpqqjonesix97\n" +
                "825seventbpqbx\n" +
                "8348\n" +
                "4dreight53rmcjrrtpcmcslbkbvphvnp3\n" +
                "eightb3pvjcczsdkghdkvjkxfpjxkgqjqgkdd5\n" +
                "sp3onejffrxblxck5one4vbvseven\n" +
                "lpsrh6five3twovvthree6\n" +
                "skhpb21zptmbvccrfcs9eight\n" +
                "pqfphhcgxz8eightwohv\n" +
                "ftbmkdgtkvvbjgpclnhrlxphgrph52five\n" +
                "two7xkccqlcdcftzmnine6sgtt\n" +
                "bbdcstgccbfivefivesix7\n" +
                "xgzvtqbjngzk7sevenvmllqm4rldvmdvmtwotwo\n" +
                "one5four3eight2five6\n" +
                "cnfcdcv6onetwoseven24one9\n" +
                "cpgthkmbqd171ninedonetwosxvt\n" +
                "onemrrzcszddxcqvfive72drksvfcbpmseven\n" +
                "twothreetwo1\n" +
                "nmsrdffmhrjjhksix54five9eight\n" +
                "ftmjgrhlqxnine8two2ninefive8bxlhqv\n" +
                "twokjp3nine\n" +
                "6mzrgjbf51onefourthree\n" +
                "threenine89zlmh9fourff\n" +
                "threefourfivej6ptg\n" +
                "864dvsfvcvhtrqzgspsbvgvvmpgjsppsvsbxrr5\n" +
                "2sixzcnqbsixvcqnvnd\n" +
                "92lthree2\n" +
                "2onegmhhnljgrf9\n" +
                "847one3\n" +
                "sixeightseven2gbvgmmmlgbmkxdnkkfqj\n" +
                "bhxdczcbpfmhjprbrqqcfcdpeight1fbbtgnc9\n" +
                "two1npqxpbrhlrfourccsfrjggltslqlhjqthreezbc8\n" +
                "dgzm48\n" +
                "svhdzdtrctppcb6flhpvvnpsk3\n" +
                "s8fourrkrlhjsnsrddhrsxzseven\n" +
                "m4\n" +
                "8rctpll4ninefds64jxl2\n" +
                "two9seven36\n" +
                "vzrmfgtmjsixfourone4fourfrnr\n" +
                "7sixpzbdmvfddfhqspkninepxrcltthree4mjbh\n" +
                "6233q32\n" +
                "gzpmvphfl5six27one4eight\n" +
                "lclqftpzgqqbls83nine9seven\n" +
                "fzztdjhsixnine91\n" +
                "9five3\n" +
                "51seven2k\n" +
                "nine6vcssmvvld4fourff6\n" +
                "bjrplzdf9seveneight1\n" +
                "82rzzlqbr8ninesmfour39\n" +
                "kzgcnine24\n" +
                "815nine6mzjpkvfhdp5\n" +
                "84mclnine5\n" +
                "phhclzqllq581vhrsk7sixeight\n" +
                "8vccclqxdskgvgqoneseven\n" +
                "szm748dqvcxlbrqbzbdnqtqsnrcpcsqtgk6\n" +
                "686135\n" +
                "fzlvnbnfctseven6eighteightxkcstfv7qjsxpfxtfzpbcsm\n" +
                "vmsxmcmffourfour1\n" +
                "lbthreednlvv16fourxzhsix\n" +
                "eightfjtpfffour4eight9nine\n" +
                "8ksonefivefour\n" +
                "3sevenbcsfour52\n" +
                "7fourzflkvskjrcxxbdfz4nkjjbgnfour5three\n" +
                "nine9xnbjnnine2\n" +
                "onejzxkqt83twoxgltxrmztlfh5\n" +
                "jtkqjfourthreefour2seven897\n" +
                "8eightvvjdmfourgfmthreedgq5\n" +
                "89two79twokxfdsk\n" +
                "onesevenfour7gflgnsmpkjmlvntxhhqtqtwo2\n" +
                "three71eight3qq62xmkzfq\n" +
                "3mvn86\n" +
                "9mgsz\n" +
                "36ninehv62\n" +
                "vdtf7fxjgjz\n" +
                "sevenxlzdftxv87fourtwo\n" +
                "fivejgzhpfkths6four\n" +
                "52fourfour7sxzptgtnhsfour82\n" +
                "ddeightwohxxcninelzptfbxczrkhmxnvt2249mn\n" +
                "xlnbvzsxjfive94ninemsb3qvkvqk8\n" +
                "kfbvvpdxrrx1threecqhqxlqnts\n" +
                "two7nine\n" +
                "2jf\n" +
                "six71lzjldpjqssxhljslsrthreefour\n" +
                "5cqcdtpsqbplkdtbtbsevenseven1two\n" +
                "2threeseven\n" +
                "1zthreenblctql9nine5\n" +
                "eightmfive714foursix3\n" +
                "1hfbdtwo\n" +
                "3czdksdsjkvcstltsbjfour2\n" +
                "7four6\n" +
                "63pggqnfg9flspklblvxlg\n" +
                "oneeightnxdfsjgkbvxonetwonine2\n" +
                "674tdqqklvthreepnlschj39\n" +
                "jk5ninerpfdlfmpfmczg3\n" +
                "qggjm3pkbskbshjbztvzxllq8six8\n" +
                "plftsevenxxmfourone15\n" +
                "seven6eightsix86onenine\n" +
                "2spngskr19nine1sevensevenksz\n" +
                "bjqbjmcrbjdfnnnhmhsmdmdksevenninermlfive3\n" +
                "lfxj63three\n" +
                "qsnvrckf4mjnoneightlgt\n" +
                "tfqqh3ninegbcdnine8hv6xl\n" +
                "41fczmhgsixtwo\n" +
                "4qmnxhnhppjhptstwothreecmxxhhfflxpxb\n" +
                "ninejbjonexkfcm13\n" +
                "tgvkft8htone7\n" +
                "99dqllhxc\n" +
                "five7mxnhb216zkjmmnjmqrplgpg\n" +
                "76gfcvlzclzcnthdkkk532frtlllmsxbv\n" +
                "6bzrvlgdbkqktzjsdsjgqmfkzdckeightcsjsrrpcl\n" +
                "qnlk4sixlfqlm8\n" +
                "1sfxdrmonectrgngdnmbfglpr\n" +
                "2974rbfourfour2\n" +
                "98nine8three1qjftl4\n" +
                "1ninelqqnpfivefour8xgzbt\n" +
                "eighttwo1one\n" +
                "1threepxdnmpmtt\n" +
                "qqfcvv5zsgcpdgh\n" +
                "3ninegcnrtwotljnbkkftfourthreefour\n" +
                "vc1nhcmvvqsix6two\n" +
                "kmpfbntsix6jdgt8bdvbfptsbkjbbvnsbrjzzhqr\n" +
                "three3fourlxnn4\n" +
                "8ninetwofour2zxgrbhjxpgbjgtpn76\n" +
                "six8six\n" +
                "qsrxjhjrk5\n" +
                "eight7sxmmmghzpmclkcbqkxvkdfnrnmqhhkkt\n" +
                "nzrgxcfl9\n" +
                "4sixtwo2five\n" +
                "sevenrpbckzzxhcfour48two\n" +
                "pbmlptjqgcxcbpslkggvqgzdpqlvztwofour9ksmzpmshcctwo\n" +
                "811sqcbjrnpxbgv\n" +
                "one6bbml7dbmpfivepgrn\n" +
                "hmfive48onevbfxrlnck4gnb1\n" +
                "2threegklleightworcg\n" +
                "zoneightphzl6lksqsxklcqthreeeighttwonsnnrtqx\n" +
                "5crfbgsevensixdfour92\n" +
                "5eight122\n" +
                "six3gcjlxrr\n" +
                "1vbzx2onenvplbkmcfzmmbbqrone\n" +
                "oneninebctxhv78\n" +
                "6xpcdqcnxq\n" +
                "sixlhkqjgmlvcbjph6threetrlpnkg\n" +
                "nsxvf31ffqlx5four7tpnzqvllkn\n" +
                "onesix4dgskfddrfivefourtrzzxfjg\n" +
                "bprxxzdd1\n" +
                "three45shjhqtthreekmvx\n" +
                "sevenjpmjthreefive8eight9txtltqjm\n" +
                "zbqsnhfnkcccseven5vfiveonexvlfbkzbd\n" +
                "6kprj6eight4jhgdgcbcfg3lcfbgfsdkg\n" +
                "fourtwo217ljzlsevenznbmgd\n" +
                "jxpszskeight5rfourone2lxphhpone\n" +
                "five4zj5pz5qfoursix\n" +
                "vncrqcsix3fourxsnf7\n" +
                "636qbxtkzroneighttpv\n" +
                "1oneightgqx\n" +
                "two2fouronehcq\n" +
                "vbsmfthreethree7mhfsgnf\n" +
                "nklpxknvbbrjbmxtxplkldvspspvlq5tpbsxklqmndmxxn7\n" +
                "3four2684\n" +
                "3sixonethreegbjzfour2mmrk4\n" +
                "jzzrkn5five\n" +
                "ninesixsk1kphntgbmzlctjtzdmgzk\n" +
                "fourvjhkzqlqfour6c1\n" +
                "38xxrrgdrgxrninefive91\n" +
                "15seven8\n" +
                "nine4one5onenineone7\n" +
                "5mfknkone4cphtbrtj1eightwon\n" +
                "vgeightlvvxlkqzzgtg368nlmmhdmmqf\n" +
                "8threeeight29jhhqjpnbbp66mlb\n" +
                "mzzm4\n" +
                "sevenfive44xvxlrxzfk\n" +
                "82seven1twozdbpks143\n" +
                "eightckfbqfgz9gzkxqmzjkhsix7eight\n" +
                "tzl184two6four\n" +
                "fkdqzcj3three64seven1jrrdvcx\n" +
                "two6jq9ninenine\n" +
                "2three2three\n" +
                "7rsix73two\n" +
                "eightrmkhpvkdhd3four2twoseven\n" +
                "knhjndmbtwofive5\n" +
                "62three72xk\n" +
                "jxjzgqszseven2\n" +
                "8l4eightndnsssf\n" +
                "gpbqt882hsszgmsxc6two\n" +
                "ppeight9four\n" +
                "two9two96two3\n" +
                "fiveglpg41fourtwo7two\n" +
                "jtwonedjjninesvzc96\n" +
                "ztzgkneightdqpvgbnhlzhvchj65\n" +
                "757seven2tjzvtmbbgbxxrmtqvtp\n" +
                "25fivezdpdvgtlql8\n" +
                "sg2bktwo6fourfourtwo\n" +
                "1six6sevenjkpgbdqnrsvlbmq\n" +
                "honeight65five3\n" +
                "nine52kjhsrzxnp\n" +
                "five33\n" +
                "qtmcbxxjceightnmjxblsixonelhbspf5\n" +
                "twoltcsmtvmone1\n" +
                "1739one9\n" +
                "13ghnine8z\n" +
                "sixfive13twotkslfhxjfdqdhcj\n" +
                "vzjngqthreethreenmlshs89\n" +
                "sixjgnt1\n" +
                "onethree776gzsmt\n" +
                "4sixxxhnq\n" +
                "krnlpckgjv722threesxrcjkcznb6foursix\n" +
                "fkvmfourvkghfivesix3nine\n" +
                "sixmsrlzbdmnclztrhhtlbj9ndgccjq7d1\n" +
                "7hphone1\n" +
                "dlhdjjcpl443rsklgp\n" +
                "lljhthreesix53bzm8\n" +
                "4sixnine2four7threeone\n" +
                "237nine1three\n" +
                "lbplmntwobxpvcbslp6hpzpbmkvbqfour\n" +
                "onecgtqtbn787\n" +
                "one8threetwortvpqqspbgfour6nine\n" +
                "672twoone334\n" +
                "four4sixxghvzxm2\n" +
                "sevengcng8\n" +
                "eight9six5sixoneptdrglllzvsrtlc\n" +
                "sixxvdhxdlxdtdqjz24q\n" +
                "1gmkthree3kqgfdkmtppshvcjzqmstwo2\n" +
                "eightfourvkrzsqxq1sevennhnine5lmptlxl\n" +
                "sixckmdbd1mrncvrcntlvjcv\n" +
                "xptwone3xtgfourtwo2k5\n" +
                "4nineninetdl1fiverpfhsbvnbpzxbvhmqpqj\n" +
                "877tjrtdr\n" +
                "n286rkmsvkzcthreeqdxdccmcd\n" +
                "1979\n" +
                "254zhtrlvpfs\n" +
                "5njg\n" +
                "1nineqftrhzkxvgtwo\n" +
                "4five675zfjrhkdkbd\n" +
                "tzxrrzc8dljzcnmxmfourthree\n" +
                "fivezcgfdvrrf2sixseven2\n" +
                "74nine\n" +
                "387fourseven2twothree\n" +
                "9six5\n" +
                "threefnrqfkqtkxqlpt67\n" +
                "66rzpmsvztwonernf\n" +
                "9nlfsdtn8\n" +
                "89zbphtctxkfqpj6\n" +
                "eightksevenchjgvctdkfbhrxssfzcgssix21oneightrt\n" +
                "drmfmxpnptqt5lmdrnhzkfcknltj4\n" +
                "fourlvtkxjlheight3nine\n" +
                "kmbftcbrxpxqk9\n" +
                "mlgeightwo1rslfrhvfdgsprbmnqpp\n" +
                "ktwone98three\n" +
                "4hvxgtjdgldjfdnfiveeight\n" +
                "gmcsixthreenffhcbnc35six\n" +
                "xt8threefhgjrmpgh2\n" +
                "pj2sv77sqgjfhzx5\n" +
                "qccfftqjmv35\n" +
                "pnrsqpsgdlgzszldvtjrfive1two4seven74\n" +
                "4nbprtcnvpvcvdg5seven85bnvnrznnncbrsh\n" +
                "qmfmkqsix8fourhnfhqn69\n" +
                "threefpgk3seven\n" +
                "1rngbxkxqthkvonethree6seven\n" +
                "7three56qlqcrsljeight1five\n" +
                "18717fzdccbglhjmvkznqvfive\n" +
                "lprmxkdnrchs27sevenone6\n" +
                "four55sixjvhbkbpdjptnhcxpmlnfour\n" +
                "eightfvdccbgxrg4bplqrvvpjq59\n" +
                "one3rxm7eightxtg41\n" +
                "fourhxplrbq7mnvnlsdcfpkdknqdtdjrpfvkp\n" +
                "7mpmrgkqfzeight\n" +
                "three9cp\n" +
                "bk3eightt\n" +
                "4glcfxkptsixjfqdnscjv2xthree8\n" +
                "bdgxxxssthree4vfqzlvdk5\n" +
                "eighttwoonefsthree35\n" +
                "sflvqvvzcs271\n" +
                "cpflsnhjrmzqmfour3rhkdtqvskt\n" +
                "ncdgjdpdtpgpztj3\n" +
                "ninevlgzpcjsixthree49\n" +
                "fqfh7one2eight\n" +
                "vvzeight16three8kqvqzj\n" +
                "nineb4fdmtlhmjbsxzrkblxm2tpqkn\n" +
                "zdtghhxfbkkdnsix7sfj\n" +
                "eightfldsxvsvmdl6onenxfsz\n" +
                "threeprbbbcxhqone9jtqjone27six\n" +
                "pstg7\n" +
                "2threethreefive4nine\n" +
                "4fourthree\n" +
                "hgj1npvqhmkm\n" +
                "43twonine\n" +
                "58t2tvtstgs8tgmfbndr\n" +
                "9xdvnrzgnz6dkvnk5\n" +
                "one31nineeight\n" +
                "1eightgzzmrqjmxtdxmxcxn5txqvhdr\n" +
                "four1seven\n" +
                "sixz12cvqlmqqzvnnhfiveoneightm\n" +
                "three5fznzbvsqnxtqnsmjt7hrhjgvqxnr\n" +
                "gmbhone5fpxjlvksevenjgh\n" +
                "fjfskl4\n" +
                "tkjqkpjddlmvmmxtxf5mdzgjone42\n" +
                "onesflmvlhfvxlrbk68\n" +
                "gfive9zhtbkvn\n" +
                "xxhsvbjxhcnqsnvnineone489nft\n" +
                "ninetwo8fiveeight1ninennls\n" +
                "xdkbsfrfz65xgjftjfhnh4\n" +
                "4threeeightsevenjsltzglonesevenzhhhcdbjfive\n" +
                "one7nnxzvhmvl\n" +
                "dcmsrd4sevenfour51five2\n" +
                "qvrgbjkgfpdbndpdgdptjqdhqkcrjknfxbgn4\n" +
                "p2\n" +
                "3311dczzvrskxksevenpgxthreeeight\n" +
                "tworbzmdd45foursevenfive\n" +
                "5fivefive7trtdlnppfournine3\n" +
                "5sixvtbfcbfkvbvbv3986\n" +
                "six64sixltlpnvt77\n" +
                "1oneeighttwo\n" +
                "tjsgchgninexrszjtzseven86\n" +
                "3cnine18\n" +
                "gntwone89glp31oneseven\n" +
                "9twofrqprtrhklhq39fjdtnnnjconejrqbgrdhhj\n" +
                "twozvmhxrhjzlhfninerbhzjxrgnmjt7\n" +
                "6five6fivezsbjjtvxvd9sixfiveqnsr\n" +
                "2threevldkrspksbsixsixtdgzmjrs2\n" +
                "fourhlstxkvr74qnx\n" +
                "one83\n" +
                "kdpdcvjlcsevensevennzvfourpvmlgttbl5\n" +
                "93smjxjpgnp8\n" +
                "dfmjhmrconetbztgfgf8six3hlbqdzqqs\n" +
                "4twotktfive\n" +
                "7nine1fscqqcml2two1fhddkblmgrtkrn\n" +
                "6fivefoureightnineninefive\n" +
                "39fourlsnmh7one\n" +
                "3fhkbpdmmgkgf\n" +
                "eightone3qjpfddljjjpjjmcg2twonexh\n" +
                "4two2517\n" +
                "seven6sixvrhjm543ckq\n" +
                "four7ninethreeonevfqrkhtx4\n" +
                "jeightwo5\n" +
                "fnndfvpc3five3h5\n" +
                "xkqstv5jpfonetwogjlbx5\n" +
                "fiveone8eightfive\n" +
                "2twomjkthreetkxtht2one\n" +
                "seven65gbmjcsmkr3\n" +
                "3qtrdtwo52eightntlbdmqcvseven\n" +
                "4cghqgpsmjztwo\n" +
                "8tqjlbpjmtwolrxp\n" +
                "ggrxfxrx15\n" +
                "3vt8sevenfourbkgcbvll28\n" +
                "lmgzcd4sixslonetwo\n" +
                "ptstwone6mpspfsevenh765eight\n" +
                "jfgpcfrgrmfnine5\n" +
                "fivec1ninefivefour9kmthmtwo\n" +
                "5zscbtpbbbbkhjrlxtnf4cmbfhbtwo\n" +
                "2mmgv\n" +
                "zmhcsixeighttwonine5gvljrkvqh\n" +
                "4five3\n" +
                "1four8six2one\n" +
                "sevenseven26mnbd7nine\n" +
                "vmxrptvk964sevendmdsql5\n" +
                "sevenfivekllbkzrmpmeight2twothree4\n" +
                "one45kjlnmznt67bgpl\n" +
                "eight7gpc6vvzqone\n" +
                "hjdbghreightthreesixzphtmj81\n" +
                "5dqftptqnfthree2nine5\n" +
                "86sixqgmlbnpnsixbxnfhmcdt8threefklhnsmkz\n" +
                "5vjgqnvvlonevxjzh9vctwo7nine\n" +
                "63ffslvtvvtgkmhvf1ntjtseven\n" +
                "fivefivev5tbpkx2\n" +
                "fourrsb5eightsfqsblmkkeightbnpqkmxxc6five\n" +
                "79kddeight\n" +
                "j5qltpmnineseventwo5\n" +
                "54gbmmmrfour\n" +
                "6ctfvjtnvdfourxjkjseven\n" +
                "1frq\n" +
                "75xhz7one4xlb\n" +
                "onetvxfive221zj2\n" +
                "sevenvkxvmqd93\n" +
                "5nfnldqtxpb35seven8\n" +
                "twobxtrpdzvbktrh1seven2two8\n" +
                "qsixeighttwofrxbxfspqmktpj5\n" +
                "2twoseven29knktthzssnhhf\n" +
                "595eightfiveeight4\n" +
                "rzmktrreight6n5seveneight\n" +
                "fivesix9\n" +
                "kqc81one\n" +
                "t271fivefournine5\n" +
                "65threefiveqfsmone\n" +
                "brhlq1eight931fourtwo\n" +
                "nine7eight\n" +
                "68nsgrvk2six\n" +
                "419gsmxnmjfour5\n" +
                "jqrh848\n" +
                "2eight91\n" +
                "sfgzxpbhb1cxjpd5ninegvpfmhkfgjkgblseven\n" +
                "dmnrmp77qqnbpvzeighttwo\n" +
                "pmgjdtdfx6\n" +
                "prrzx4jfjzpcklsb5sevenfour7six\n" +
                "brsqmz38five5twonebp\n" +
                "seven4threefour\n" +
                "18gmfvqgteight\n" +
                "7oneeightfourseven\n" +
                "onepkfnnvjpkgbvt8\n" +
                "fourkj4onenlkjcrvl\n" +
                "1phb5\n" +
                "16thgsmdqbnfivethreehbmmninenine\n" +
                "9qfqhdgthreeqmdg9cjzkjckfttwo\n" +
                "dxsevenone1mxmcfkgtdsczbgsx8\n" +
                "9jmhxphrhrjqmnnine3rxfmhjjqt\n" +
                "fivevjrninethreeseven6eight4\n" +
                "gltmpctwopcbchlj9r91qbdvsz\n" +
                "nmskpljnffbtwo7ffive5kqr\n" +
                "hlceightwotwoctsix4kkppmcxh\n" +
                "7vdtbxbsdm9nine9mqbgzgb6\n" +
                "threethreeeight4lfshmkpsbrveightsix\n" +
                "s77eighttwo\n" +
                "kxgntkmxshkllhctzk14\n" +
                "eight9lks3574\n" +
                "66fourstxmfqzpseven8p\n" +
                "46nine1twocqcqzn\n" +
                "vvzmqcj5fiverrj3threepltjs\n" +
                "2blshrhbpsnqqgxtnlzthreefour\n" +
                "4bqcssvxmxtwoeight4threeonenine\n" +
                "onezphmrtxbtlczz5eight\n" +
                "qcvvlc92mhhqpfsrrfndgl\n" +
                "seventwo5\n" +
                "2eight5oneeighteighteight32\n" +
                "cbmbfsztjnine3ztzbk49lvvlknvrnn\n" +
                "4qbtglxjhzb\n" +
                "5qzrlv4nxlxzbcdjsevenseven2jphvkthb\n" +
                "seven56\n" +
                "fivejlpnftwo7nz4fiveone\n" +
                "53hszlseven\n" +
                "tzr5sevenone5\n" +
                "ninegmzppseven7\n" +
                "dhrcgzqctwoeight8qhtlpf5jhvbcl\n" +
                "98onetwo715tcg5\n" +
                "tlfoursix5gzbntsevenseven\n" +
                "eight7peightonetwo937\n" +
                "6djvpnxvgfvbzpbgh5fk\n" +
                "ktxcqsgjthreesevenjrsgddzrfour8\n" +
                "lqmvrqgtdcmtzprq9threefour11jjkffcd\n" +
                "kbnlmsixfivetwohxftxpmvfn7\n" +
                "1qhf239nine\n" +
                "125zdjtsdxmthreeeight22eight\n" +
                "37\n" +
                "five827\n" +
                "lzn25\n" +
                "cspdsgf41nsjlthreedpcmq1nine\n" +
                "flvgklrtwodpxk2twobg57\n" +
                "8seven5nine\n" +
                "82seventpqmczz28fiveone\n" +
                "854vtxbrr2\n" +
                "three6seven6sevenonejsqtjpt\n" +
                "sixzbsxxngxcninesix82\n" +
                "mrbsp8sevenjhsfxgvpbv8\n" +
                "nine9kh\n" +
                "6fhzkrxsxthreeone\n" +
                "tvpmseven3fthlkndskdgfhjrvcxcninetdlkgrnxpm\n" +
                "tbrgbllqffourfqthree2\n" +
                "1sixvtmjtwokb71bddxpv\n" +
                "twolsjbscrfjzjsnphgsbthsmch6two5\n" +
                "3fouroneeightvbxsixb2\n" +
                "41dbqvfthree\n" +
                "tjjtpjpg1\n" +
                "6rfmfouronethreezgjsprtmd1sixeight\n" +
                "six182tbjjx7\n" +
                "4ffsgbshfzq93five\n" +
                "4threecncqtdklqt\n" +
                "nrkkgxzlsevenrqhbvzfvn99oneqjlxld9\n" +
                "xchnxhmfhpfiveblccdzdnqbzbm8gjrbqdslbbhdxpbpm\n" +
                "hbfdlrxmkrbc9threeonefive1rrvlfgjrq4\n" +
                "1eightthreeclpnzrtfive2\n" +
                "4nine1lsmmjjhsbninehlfxbbmsjcone\n" +
                "four16seven3fhvhlhcrmone\n" +
                "qszfive3sixbcdkcmdqhj3six\n" +
                "eightonelmbjb1cfx\n" +
                "3three1sixsix7\n" +
                "1cnmrhxhzrkshqnpqmfour8fqlfzq\n" +
                "two9sixbcgpv2rnnkdpeightthreenine\n" +
                "vbzqpkmqtpbfourseven6bhzghsix6\n" +
                "fhtwone26sixtwothreeseven\n" +
                "jvoneight7eightdfvljxthreethreefoureightkvb6\n" +
                "6hrnfhcn2nlflcj\n" +
                "gqktqlbkbeightninehvfql3lbfllrnrblqchfmn6pknq\n" +
                "twosix4nine\n" +
                "36sevenzlzgftkzznxqpnrbhtwoeightfive\n" +
                "qxqckssnrd8sdprgknine\n" +
                "1seventwoseven\n" +
                "mnfhgnrlfzfive1\n" +
                "pghfiveeightseven4nfzlkgdcvk\n" +
                "jvcmsdlfeight4\n" +
                "dtmt1sixkgmvnfvqd1sjvslttcfmkgngkrmbsmd\n" +
                "gltskr21\n" +
                "vvqoneightmfkbp61qkdpsvlhqctfseventhree\n" +
                "qvggksmf1\n" +
                "xhmzv926sixlqtwoeight\n" +
                "647six51\n" +
                "5qbx5seven8oneeight\n" +
                "mmcktfzstwoblzthssjnine1\n" +
                "558\n" +
                "48threenine4hlfdjnxdpnine8\n" +
                "hsghqrmpzbqsl7flbcjqqmrxkkcghdzmthreesix\n" +
                "27tldnbdsixtwosevennjdjxz\n" +
                "sevensixsbphqrqtqs9983\n" +
                "7eightsixzrktkone\n" +
                "91npjhccblmpxtslz78kcvqtvqpmone\n" +
                "tnshjg21twothreeonesxkpgctcjdjpxt\n" +
                "six9twothreeqx4one6one\n" +
                "ninenine6npnszkvcgn\n" +
                "four5threenineone6\n" +
                "4twobgdhnbtcssevenmmzfgktwo4\n" +
                "three38\n" +
                "ndfplbcdsnrhgpq1two4\n" +
                "xhdfzl78twofivethree\n" +
                "zqcccjkgrdnr5cxmfhthreeskzcqkczp\n" +
                "vltlfh1qfdzgp8five\n" +
                "mqjnsx99ninetwo8\n" +
                "bnk7\n" +
                "dqk62ninegvhbmclnrfztmtfvrzjrv\n" +
                "85dnine3lkzmn\n" +
                "onesixthreekdrgmlnddsc7\n" +
                "sds6\n" +
                "9vkhr49sixxgqbgmsheightfive6\n" +
                "onetwoxrhzg1ninefourseven32\n" +
                "fsthreeczsqjcjlxqxgxrbfour8nine\n" +
                "threeseven576vrvj7d7eightwogc\n" +
                "6rfpeightfive4zsrnsvvbdd\n" +
                "3fiver6nnpmgmhzlhzfxb16jg\n" +
                "three9qhlpninethreethreemfr7\n" +
                "rx6dhk1sjrpmpjr\n" +
                "three4nhvkksevenxzbzbflnrcmmzg\n" +
                "eightvckzjgonetkcvjzdhnzfoursix6\n" +
                "onetwothreednktwoseight7jkpsgtdllf\n" +
                "nx6eight13nine\n" +
                "qzvnvsjnfjng99threesevenvc\n" +
                "seven2eightbpzsix\n" +
                "onefour8xccmksgfsckxkbcsqkgdgszxjgllh\n" +
                "8zfour\n" +
                "fiveeightrssqtwo992\n" +
                "8nbvcfjzpxnpfour4\n" +
                "zhqmxqlzv6onetwoeightkrfg25two\n" +
                "9tqbeightfmgqtdbl\n" +
                "three3nine97\n" +
                "vpcmmlctgc6\n" +
                "3two4fhnh2ninesixmtfbbvdkls6\n" +
                "171\n" +
                "lveightwofive8ninetwo3sixzp\n" +
                "3oneqhgonerjskld3eight5\n" +
                "zfxnkhrthreexllntwo1two9fivetwo\n" +
                "sixfivexmxxq7\n" +
                "xxhthqxnjq3tgjdvrnqtgts9\n" +
                "7226fiveqzbvgttlmv\n" +
                "884xxxt9\n" +
                "781\n" +
                "4dtpcdslmg9mdxsjksixnine\n" +
                "onesevenkqzg2\n" +
                "nine4nine\n" +
                "cdqmrvdkxtrqdsixnvqxs4fiveninefvdttbqkx\n" +
                "blcbcgbrnkpmlrdlj7fivedbnkkleightone94\n" +
                "1hgtmpdlpsfivethree8four5\n" +
                "vx93czsixkzkjpqbgzhthreetwo\n" +
                "zfbxmsjrmssixninebkvseventl69\n" +
                "jcnkdqmdvg392\n" +
                "pqkgqzgtwo245two9\n" +
                "1zzjc7onejdf5snc\n" +
                "25dhcpqbkzjxcxmxdgxftj\n" +
                "kzqsix8xblzlnjtvbfive5four35\n" +
                "ghfjjhphnftwo9five\n" +
                "jqstpxv5hcqfbh7twotwofive\n" +
                "jj66nsixhfsbgs6kmdpqdrpn\n" +
                "xfvc73snqtcpqcjlsix6526\n" +
                "tbpklzqjcz6fttcvqd\n" +
                "9pdrzfvrr9twolzgs\n" +
                "fiveseventhreeszxkxjx9ndvtlhqqqh7spfcvpzthree\n" +
                "68blhzlngj7\n" +
                "hznljt4eight8qfkhmqvpskcxknz9\n" +
                "eightjqlghmn76two5ggone\n" +
                "onesixmgbfjv41fhoneightvxl\n" +
                "jjlthreenine839\n" +
                "twotwo4xvlpcnpmtwo2jrzcjjlfteighteightwotv\n" +
                "t4\n" +
                "onefivefivefour94eightfour\n" +
                "6sixtj6threethree2sevenone\n" +
                "1eightkbsixrhhphnxmjlf\n" +
                "mlplpjkndlflk1nineninetndsqjnpmvzhkeight\n" +
                "jmkqqblqnxfivetwo8485eightone\n" +
                "five9565three3nineseven\n" +
                "bmfljlbbttxlvxzrfnnp319six\n" +
                "jb4one96\n" +
                "jqllbjqndlkbxkeightdrbhjjd3\n" +
                "8fiveggdtrfjvrpd7six7\n" +
                "24xrt3twosix2\n" +
                "rccf47zzmfshdtwosrsm\n" +
                "5jtqxkpshnbtwohtpbgtgsixone\n" +
                "seven77p\n" +
                "eightqgkmdvhdjssqfpfnk3sixthreesixthree\n" +
                "9ninetwoonelkrspqn3\n" +
                "4ttdgvkghzlninevkrxhclmstdq9mpmgtcvrlqvlqgtrxb\n" +
                "two7twojxzbrhtnpfrhpvsevenfive\n" +
                "4threetbkddx252tmspeight\n" +
                "five9xbcrfrxbdnb\n" +
                "threetwo6seven2foursix\n" +
                "onekeightxdgxjmthreeszrjhmk9\n" +
                "6q565cvdhbjldkb\n" +
                "two1three\n" +
                "dzrhvfktjninepfxvxmzmkeight1\n" +
                "xzbgjqfour5nphmrhlfdkk\n" +
                "38rfjeight5\n" +
                "848bfztdm\n" +
                "rldlk2zbmpsl8\n" +
                "gqgtrchtwoeight9eightone\n" +
                "27f\n" +
                "btgxvnm8seven2\n" +
                "sixmznpvvsbrslmtgfpvctz96hrjdlclnzmftjjdmp3\n" +
                "hsppfkeightsevenfive2\n" +
                "2two35kxssnjs21three\n" +
                "3ninefivemjslrzzsnl\n" +
                "9lzdmtdeightone3smfpmlvs5zkxmrssq\n" +
                "zrgsrbgcrllnjfrk9eightsevenlflnkxfgbzm\n" +
                "ninexsgvvslvvczfshvgfour6ngkkmcrkgbsngkzvcch\n" +
                "26six997\n" +
                "1zbsth\n" +
                "psdksevenone776\n" +
                "one8lzcrggjfrjssixkjtwo\n" +
                "sevenfour5three91six\n" +
                "brg3ninetwo5rvnpqsix\n" +
                "9seven9sixssnfourxsdbgbrpvxcmqh\n" +
                "6cmcheight8\n" +
                "onefive1sevenfournine1\n" +
                "threej3\n" +
                "lmzq27kkzxbtwo142\n" +
                "krhhmmsrklseven5pmjpthree8\n" +
                "lgplxpx7eighttlvqdmmlhz9gjfbxnlkkg\n" +
                "tfrpbxpsbghffsixrgm4\n" +
                "8fjnflxr2613\n" +
                "7onevzqcgqsevenrgs3twonex\n" +
                "8nine9brsnqlvtfivefour4fourtknbsm\n" +
                "grct7svvdbqtsrxsix9\n" +
                "544\n" +
                "bldknmxccsix4\n" +
                "xjdxzmhxqbfive36frtstwothree\n" +
                "4two7nine\n" +
                "8five99jddntnhjjsxjgfsqhljcrq\n" +
                "twotwofivethreeseven4tzgnqcq\n" +
                "sevenlvxjjrsjzvjxsltlfour2qmqtbklpkp\n" +
                "sixvrlseven1twothree\n" +
                "fivepcrhdtkrfour2snvjhhqzl8cbfkgghvb7\n" +
                "mhhfjmv4nine6rvdvhjlfgsixjzghsdf5\n" +
                "7fgmnvtfn94qbtrfb26\n" +
                "threeonejxjkcz2\n" +
                "1eighteightfour9xxdqnine\n" +
                "3threefour932\n" +
                "mtnp6onefour4oneseven3cjcm\n" +
                "fivetwo7four\n" +
                "sevenrtbx6trxfffsdlgztwo3\n" +
                "eight16fiveoneninejnpvnglzjd\n" +
                "7pqvfjeight\n" +
                "two87sbseven88\n" +
                "73678seven4three\n" +
                "pmxdvndvsixcvnntjcv4sevenhfmklmztwoeight\n" +
                "pdplkff87fouronefqrrbnine8djkgh\n" +
                "eight35vlllkzmnlpcgngjnt\n" +
                "897kqjhkfhfbone\n" +
                "ch6\n" +
                "5threefivehfnvsphfxqdltgtbjtwofour3\n" +
                "nine5fourfivejtrhmnbmx\n" +
                "eightqthree5gdpvnt2eightpbd\n" +
                "jbv34nine\n" +
                "lcqxvbhr1\n" +
                "4dpcbxj\n" +
                "seven3eight75\n" +
                "75ronenine4four\n" +
                "4ppfnkjpphppsjr4\n" +
                "2cjkjnvnjxtwolhmnrlcpzmbkhzjkcvknczjvcxj\n" +
                "tj5rgmvvhmc2\n" +
                "three7scghxlnbsmgtjgqqtmxrfnvtlvcpp16\n" +
                "fiveonefourxlqcttwosnine9\n" +
                "323hmpxbkpdvklcrnglmhdlcmmzdtwo\n" +
                "onevvbvctdqsvhqb9\n" +
                "4foursix3\n" +
                "56seveneight281five\n" +
                "5t1ldfbstvrvbks2sevengfndh\n" +
                "6four48\n" +
                "4fmgjxzxhq\n" +
                "sixkmltvqjv6qfpf235\n" +
                "three4djpcgvbone1bztqnhk\n" +
                "5fourfjtflgsixtwofourthree\n" +
                "4nine9gcdnfjm\n" +
                "xfcnmpbvmmhkfiveseven88v6\n" +
                "68sixtworztsbzvghjsmchmsxmdnine\n" +
                "seven1eight\n" +
                "3threesxjqxxx2threeeight2\n" +
                "twontnxvnjjtwocpxmrsix2x2nc\n" +
                "nineltgzzzzqg2sixnxdhcb36\n" +
                "623twohnmqptwo8\n" +
                "ntwonebtcqztrvninenine58glpkdpdghkbtrsz\n" +
                "rlnthmmdfsvmdfqhfivendptjfpx7hnbnkzlpntvglvdlfb4five\n" +
                "cmx6four6\n" +
                "81ninefourqbljfrbshsnmcqmzrhkznl\n" +
                "psixthree8jrmhcvpdgflsnnvdgmkxtxrl\n" +
                "2ggghpzxxlmrlftpqmsg\n" +
                "7four296nine\n" +
                "2xonesevenonenine39ctq\n" +
                "four915fdtcvcrv\n" +
                "fsssjgbncc8nine\n" +
                "qgpfveightdvtkhxxzrcmfivesix4\n" +
                "4436eightonefspnbptktv\n" +
                "rlmmlrhmjnfivetwo6sixmxs\n" +
                "443ninesixfour\n" +
                "fivexmcdmpxfcn8ddnrhbl9znqxtf\n" +
                "djtkclphr4ninesixfiveqgksrzj6nineeightwogz\n" +
                "eight494dd\n" +
                "klmmxtlvxsnineeightrxzzksjxcvgvznonevbnhxjlrxh85\n" +
                "vftdg4fvlseven9fnh\n" +
                "rglcjdkcsevenrvrkrrptx4mfbqb\n" +
                "767five9\n" +
                "eight1four3\n" +
                "fourfived84threethreeeight\n" +
                "two5foureight\n" +
                "seven43gzzmksixhmln2\n" +
                "bjknl46ninexrjbr5fourfour\n" +
                "2pns7fpjznxkponepfive\n" +
                "sixkqdhm1ninetwor7\n" +
                "threefive8\n" +
                "two8lhlphf\n" +
                "seven3seventwo\n" +
                "4psqnsmqgz25\n" +
                "eight33fiveg5oneeightwoh\n" +
                "sixsixxldfive8\n" +
                "qhljssjbsevengfh5seven\n" +
                "gjsqptqkjk3bhj6five\n" +
                "six6szlss9seven\n" +
                "nmzxrgthreemtckbvglb7six\n" +
                "ffxmfive392fivethreenineseven\n" +
                "sevenvvnssgvrq8ninedfvqzgrdtqnh\n" +
                "hbsgz8nineczksxzllx2five\n" +
                "9twonine\n" +
                "4fz\n" +
                "3fqjnpxnvseventhree7ninefive9\n" +
                "phlvsix123pszgrxvhjkk\n" +
                "3two4\n" +
                "klcbnvrfv31zbb236\n" +
                "eightseven1lkcv1six9\n" +
                "7four7fiveeight\n" +
                "lqninenmqmbsgk9\n" +
                "sevensixmczghz299six\n" +
                "49sixlcbtsbnineseven9five\n" +
                "rtwone36sblhninemflhd\n" +
                "8nineblqjzsddone24dnfdgph\n" +
                "jzlbhlhvfour4dlvctlrqsix\n" +
                "threeseventhreenlhcc8\n" +
                "2xgccjbmdlzlstjvqsknd\n" +
                "97ninedfcmx9359l\n" +
                "7sevenqzvlfqlfsdxsix\n" +
                "8682\n" +
                "2bhzhzpglp\n" +
                "sevenzbfvlpn7tkhmxtvgvfeightwobsb\n" +
                "npdfzsevenonezc1two\n" +
                "2hcmrldtn5\n" +
                "threeseven286fourfour\n" +
                "seventwo5eight\n" +
                "ninefourmqxjdthczlqp4xrxrptzvdllctwo\n" +
                "ninefour8\n" +
                "q52xzpxvkgsixctrjg\n" +
                "6four52qkvtqpqcfivevghjmltckgtjjf\n" +
                "qxxkgqqcggbjc85\n" +
                "lninelbzqtdbnvvmchxrpsbfivehtmqcc3\n" +
                "xbtlshzqtrtwo8sqffcsfivetwo3mvxsnkgseven\n" +
                "5pqlfrqqhpgtg6four\n" +
                "6lxjzthree14six4\n" +
                "three22fxrrdvk\n" +
                "sixztwoeightnine4seven1four\n" +
                "fivegbvrtkvldplfzrvxbmkmrcftxs4oneqhmxseventhree\n" +
                "threenine2vzdkxtz7\n" +
                "7mnmfkfq48\n" +
                "four66grzkq86six\n" +
                "four3threezdszkzkbhnsqpmsninebq\n" +
                "746\n" +
                "55fiveqhvtgfz\n" +
                "c2mjsrdzmtsevenfive6ncjrvzc4\n" +
                "ntwoneeight2five93jskvfcvn\n" +
                "fvzjvxtwozhnhnmqv3seventhree\n" +
                "2three5three\n" +
                "2sevenclone1\n" +
                "three9two4kqxq7four\n" +
                "eight8gzhcfbjxjnftxnnjl\n" +
                "mkz4two7fivefive9fivethree\n" +
                "eighttwo9seven6\n" +
                "eightkdpfprqdz6\n" +
                "9twofczb\n" +
                "sqmhjgzqvc3\n" +
                "525three9jnppn\n" +
                "eightkpfngjsx97twozmbdtxhh\n" +
                "snc6\n" +
                "two3dqpnps3pmdnbxdnlc8\n" +
                "pfnv2\n" +
                "four1sixeightm35\n" +
                "sixldzmvtfsthreeseven1ninethreeseveneight\n" +
                "7jrxgdjfh3xvlpfgckjp6fourfive\n" +
                "sktmpngljrrgvpqqkdnine14d\n" +
                "one79\n" +
                "1five7jmhtbnkvcg8vgrxdbnr5four\n" +
                "fvzcslpmgv174426\n" +
                "3nineccslpsrfdf35lqbfqbncs83\n" +
                "364twoqvqr4\n" +
                "79lfd2nineeight2ghrlbspvkzseven\n" +
                "nine1ztqbs\n" +
                "eightndxxqxtwo3cqz47\n" +
                "fiveeight792eightqskstrftdpccsrgskrhc\n" +
                "26fmrrhhpthree6b";
    }
}
